import 'bootstrap/dist/css/bootstrap.min.css'
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Provider } from 'react-redux'
import { store } from '../store/features/store'
// import { store } from '../store/Count/store'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className="container">
      <Provider store={store}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/title_tree.png" />
        </Head>
        <Component {...pageProps} />
      </Provider>
    </div>
  )
}

export default MyApp
